# Generated by Django 6.0.3 on 2026-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('investor', 'Investor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
