# Generated by Django 5.1.7 on 2025-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='business_model',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='business_stage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='competitive_landscape',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='current_traction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='customer_acquisition_strategy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='development_stage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='development_timeline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='existing_solutions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='funding_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='hiring_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='idea',
            name='key_challenges',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='key_features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='market_size_estimation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='market_trend',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='idea_pitches/'),
        ),
        migrations.AddField(
            model_name='idea',
            name='pricing_strategy',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='problem_scale',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='problem_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='problem_urgency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='revenue_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='target_market',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='team_vision',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='technologies_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='unique_value_proposition',
            field=models.TextField(blank=True, default=''),
        ),
    ]
