# Generated by Django 6.0.3 on 2026-07-28 13:24

import django.core.validators
import startups.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='idea_pitches/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'doc', 'docx']), startups.validators.validate_file_size]),
        ),
    ]
